import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const wasmPath = resolve(root, "src/wasm/scanner.wasm");
const outPath = resolve(root, "src/wasm/scannerWasm.ts");

const wasm = readFileSync(wasmPath);
const b64 = wasm.toString("base64");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `// AUTO-GENERATED by scripts/embedWasm.mjs from assembly/scanner.ts.\n` +
    `// Do not edit; run \`npm run build:wasm\` to regenerate. (${wasm.length} bytes)\n` +
    `export const SCANNER_WASM_BASE64 =\n  "${b64}";\n`,
);

console.log(`embedWasm: wrote ${outPath} (${wasm.length} wasm bytes)`);
